### ISSUE TITLE
Revert in a test for `ConvergentCurvePool`'s constructor due to an expired timestamp

### ISSUE THREAD

**Issue by cameel** [element-fi/elf-contracts#243]
The test suite started failing yesterday due to a revert in `ConvergentCurvePool`'s constructor. The revert happens at this line:
https://github.com/element-fi/elf-contracts/blob/87f8b5e8b66e041562cc775abfbce1ffed825ce2/contracts/ConvergentCurvePool.sol#L90

In the above:
- `block.timestamp` is `1629054301` (i.e. 2021-08-15 19:05:01 UTC)
- `seconds` is `Math.round(new Date().getTime() / 1000) + SECONDS_IN_YEAR / 2`.
- `_unitSeconds` is `SECONDS_IN_YEAR`.

Looks like the test sets expiration time to half a year, runs on forked mainnet forked and the the time it sets has just expired. It should be updated.

### How to reproduce
```bash
git clone https://github.com/element-fi/elf-contracts
cd elf-contracts
chmod +x scripts/load-balancer-contracts.sh
scripts/load-balancer-contracts.sh
npm install
npm run build
npx hardhat test --config hardhat.config.test.ts ./test/convergentCurvePoolTests.ts
```

```
  22 passing (14s)
  1 failing

  1) ConvergentCurvePool
       Pool Factory works
         Deploys pools:
     Error: Transaction reverted without a reason string
      at ConvergentCurvePool.constructor (contracts/ConvergentCurvePool.sol:92)
      at ConvergentPoolFactory.create (contracts/factories/ConvergentPoolFactory.sol:55)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:110:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by pvienhage** [comment]
Thanks for the diagnoses @cameel, we've shipped a fix for the test.

**Comment by cameel** [comment]
Great. Thanks!
